In [1]:
import numpy as np
import lovely_numpy as ln
import json_tricks



In [2]:
inputs = json_tricks.load('inputs/inputs.json')
answer = {}

# Task

Code the orthonormalization algorithm: it should accept the column matrix with vectors and it should return orthonormalized cooumn matrix of vectors that were orthonormalized in the order from the first one to the last one.

To make the algorithm stable from the point of view of division, divide not with the length of the vector, but with length plus some small value `eps`. This way your algorithm will never return division by zero, and the problematic vectors will be highlighted by the vectors in the result that have zero length.

In [7]:
def orthonormalization(X, eps=1e-8):
    n_vectors = X.shape[1]
    result = []

    for i in range(n_vectors):
        v = X[:, i].copy()

        for u in result:
            v -= np.dot(u, v) * u

        norm = np.linalg.norm(v)
        v /= (norm + eps)

        result.append(v)

    return np.column_stack(result)


In [8]:
answer['orthonormalized'] = []
for inp in inputs:
    Y = orthonormalization(**inp)

    answer['orthonormalized'].append(Y)

    for index in range(Y.shape[1]):
        for index2 in range(Y.shape[1]):
            if index != index2:
                pass
                assert np.abs(Y[:, index] * Y[:, index2]).sum() > 0.0e-4, "Different vectors should be orthogonal or zero"

    print('y: \n', Y)

y: 
 [[ 0.28426762 -0.07058898 -0.26327285 -0.47987233  0.7317216 ]
 [ 0.          0.         -0.4449226  -0.17246366 -0.3024976 ]
 [-0.63960215  0.23478508 -0.09984513 -0.46349357 -0.22935108]
 [ 0.07106691  0.05831263  0.41783961 -0.23778974  0.02337123]
 [ 0.28426762  0.23325054  0.65439251 -0.20386104 -0.13879498]
 [-0.56853524 -0.31458132  0.32591453 -0.1949881   0.33110922]
 [-0.28426762  0.60230813  0.01004638  0.51042422  0.43577806]
 [-0.14213381 -0.64834442  0.11671133  0.35846341  0.0336257 ]]
y: 
 [[-0.25264558  0.31170515 -0.70411107  0.57941799 -0.0866747  -0.49110158]
 [ 0.58950634 -0.01903543 -0.60405682 -0.49683203 -0.20098061 -0.14627434]
 [-0.58950634  0.46636801 -0.01073283 -0.57046235 -0.33081816 -0.25536844]
 [ 0.25264558  0.69479316  0.06921834 -0.08001797  0.66501025 -0.16590728]
 [ 0.42107596  0.44971201  0.36665595  0.29257913 -0.63278353 -0.61831474]]
y: 
 [[ 0.16384638 -0.67659659  0.21970735 -0.63689137  0.24548044 -0.03476803
   0.91217097  0.10617264]
 [ 

In [9]:
json_tricks.dump(answer, '.answer.json')

'{"orthonormalized": [{"__ndarray__": [[0.2842676216054604, -0.07058897852132079, -0.2632728501500025, -0.4798723256005069, 0.7317215981569276], [0.0, 0.0, -0.44492259690123637, -0.17246365947937262, -0.30249760202428966], [-0.6396021486122858, 0.23478508084192296, -0.09984512691263737, -0.46349356742136494, -0.22935108130946744], [0.0710669054013651, 0.05831263453862098, 0.4178396109513382, -0.23778973848194576, 0.02337122850396667], [0.2842676216054604, 0.23325053815448393, 0.6543925080310983, -0.2038610399962129, -0.13879498078419486], [-0.5685352432109207, -0.31458131797106553, 0.3259145262673355, -0.19498810241891462, 0.33110922347487254], [-0.2842676216054604, 0.602308132703979, 0.010046375629619722, 0.5104242229263978, 0.43577805930577534], [-0.1421338108027302, -0.6483444232599003, 0.11671133346250623, 0.3584634116960083, 0.0336256969628589]], "dtype": "float64", "shape": [8, 5], "Corder": true}, {"__ndarray__": [[-0.25264557610718974, 0.3117051506303324, -0.7041110689745199, 0